apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-storage
  labels:
    app: restaurant-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-storage
  template:
    metadata:
      name: restaurant-storage
      labels:
        app: restaurant-storage
    spec:
      containers:
        - name: restaurant-storage
          image: ethic19/restaurant_storage:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6060
              protocol: TCP
          env:
            - name: URL
              value: "jdbc:postgresql://postgres:5432/restaurant_storage"
            - name: USERNAME
              value: "postgres"
            - name: PASSWORD
              value: "8246"


      