apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    app: restaurant-storage
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
