apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-storage
  labels:
    app: restaurant-storage
spec:
  replicas: 5
  selector:
    matchLabels:
      app: restaurant-storage
  template:
    metadata:
      labels:
        app: restaurant-storage
    spec:
      containers:
        - name: restaurant-storage
          image: ethic19/restaurant-storage:2.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: URL
              value: "jdbc:postgresql://postgres:5432/restaurant_storage"
            - name: USERNAME
              value: "postgres"
            - name: PASSWORD
              value: "8246"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
